apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argocd-secret
  namespace: openshift-gitops
data:
  password: Z2hwXzIwRmNRQkZXZzhLMjFiTnY4VENpNWRqRjBTVzI4dDBwbEFYUg==
  username: ZnJvYmVyZ2U=