apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: openshift-gitops
kind: ConfigMap
data:
  repositories: |
    - url: https://github.com/froberge/aws-ocp-demo
      type: git
      passwordSecret:
        key: password
        name: argocd-secret
      usernameSecret:
        key: username
        name: argocd-secret
