apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: simple-quarkus-pipeline
type: Opaque
data:
  token: ${{ secrets.GITHUB_ENCRYPTED_TOKEN }}
  username: ${{ secrets.GITHUB_ENCRYPTED_USERNAME }}
  email: ${{ secrets.GITHUB_ENCRYPTED_EMAIL }}