apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: localadmins
users:
  - froberge
  - ddobrescu
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: add-cluster-role-to-group
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: localadmins