kind: Secret
apiVersion: v1
metadata:
  name: htpasswd
  namespace: openshift-config
data:
  htpasswd: >-
    ZGRvYnJlc2N1OiQyeSQwNSR2eEtyMEt1Z2l6SVRkdUpodEJ0L011a1R3RWZEZ0xsR3VPWXdqcTBHUGY2Z0lwQkxwclhVdQpmcm9iZXJnZTokMnkkMDUkTUk1VHYyWTdBY0hCS0VBVUswVVN0T3FOZEVOU21aL3hQeElENEw5RTE4WEVDbXZEaXkuVVcK
type: Opaque
