apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-quarkus-dev
spec:
  destination:
    namespace: simple-quarkus-dev
    server: https://kubernetes.default.svc
  project: simple-quarkus
  source:
    path: gitops/service-deploy/app/overlays/dev
    repoURL: https://github.com/froberge/aws-ocp-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
