
apiVersion: v1
kind: ConfigMap
metadata:
  name: console-custom-logo
  namespace: openshift-config
binaryData:
  console-custom-logo.png: ZGF0YTppbWFnZS9wbmc7YmFzZTY0LGlWQk9SdzBLR2dvQUFBQU5TVWhFVWdBQUFId0FBQUF4Q0FZQUFBQVkyTTBNQUFBQUFYTlNSMElBcnM0YzZRQUFBRVJsV0VsbVRVMEFLZ0FBQUFnQUFZZHBBQVFBQUFBQkFBQUFHZ0FBQUFBQUE2QUJBQU1BQUFBQkFBRUFBS0FDQUFRQUFBQUJBQUFBZktBREFBUUFBQUFCQUFBQU1RQUFBQUF1Q1VnWkFBQVVya2xFUVZSNEFlMWJDWFJVMVpiZFZaVTVoQ0dNQ1VPQUJJaU1NaHNFR1FSRmphQ3NkcWw4ditnU3RRWDcweXJhMnFMb1Yxa092N1VGNXlVcThyOEtJb2dOQ3FnMENBRVpSQ0VZRUF4alpKNUQ1bFM5M3Z0V2JxZ2ZRNmdFZ3IwZ2Q2M0tlKzhPNTk1NzlwbnVlUyt1bzBlUE9xZ3BGdzBIM0JmTlRtczJhamhRQS9oRkpnZzF