apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: simple-quarkus-prod

resources:
- ../../base/

patchesJson6902:
- path: deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: simple-quarkus-service
    version: v1
images:
- name: quay.io/froberge/simple-quarkus-service
  newTag: v3
